# Generated by Django 4.2.24 on 2025-10-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
